drop table if exists message;
create table if not exists message(
    id int generated by default as IDENTITY primary key,
    key int not null,
    message_date timestamp not null,
    message varchar(100) not null
);

drop table if exists counter;
create table counter(
    id int generated by default as IDENTITY primary key,
    value int not null
);